name: Publish Image

on:
  release:
    types: [created]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./publish.sh
        env:
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_TAG_VERSION: ${{ github.event.release.tag_name }}
          DOCKER_HUB_REPO: dejavumoney/anchor-ci
